### ISSUE TITLE
How to use this with @gridsome/source-graphql?

### ISSUE THREAD

**Issue by SuiOni** [noxify/gridsome-plugin-remote-image#22]
I tried to use this with graphql endpoint as source with no luck. 
The data comes from a strapi headless cms. 

Can you provide an example?

Thank you so much!

**Comment by noxify** [comment]
Hi @SuiOni,

Currently it's not possible to use this plugin with any source plugin which uses `@gridsome/graphql`.

Reason: We can't modify a remote schema.

Sorry.
