### ISSUE TITLE
Unable to download images from contentful source

### ISSUE THREAD

**Issue by noxify** [noxify/gridsome-plugin-remote-image#23]
While trying to download an image from a contentful source, the download fails and the target field has the same value as the source field.

Rootcause:
The image url inside the contentful aaset collection is `//`. The image download plugin requires `https://` or `http://`.

Solution:
Check the download url and add the missing protocol if needed.

**Comment by travis-r6s** [comment]
As a fix in the meantime, you can use `onCreateNode` to add that missing protocol:
`gridsome.server.js`
```js
module.exports = api => {
	api.onCreateNode(node => {
		if (node.internal.typeName === 'ContentfulAsset') {
			node.file.url = `https:${node.file.url}`
		}
	})
}
```

**Comment by noxify** [comment]
@DouglasKGlover - this should fix your problem :)

**Comment by DouglasKGlover** [comment]
@noxify Thanks a lot for handling this!

**Comment by noxify** [comment]
If something isn't working, feel free to create an issue here :)
