### ISSUE TITLE
Unable to download image through WordPress Source

### ISSUE THREAD

**Issue by Rocketpilot** [noxify/gridsome-plugin-remote-image#26]
Basically, no matter what I try, "imageDownloaded" returns a null value.

The setup:

In gridsome.config.js

```js
plugins: [
		{
			use: '@gridsome/source-wordpress',
			options: {
				baseUrl: 'https://sitename', // required
				typeName: 'WordPress', // GraphQL schema name (Optional)
			},
		},
		{
			use: '@noxify/gridsome-plugin-remote-image',
			options: {
				typeName: 'WordPressCustompagetype',
				sourceField: 'bannerImage',
				targetField: 'imageDownloaded',
				targetPath: './src/remoteImages',
			},
		},
	],
```

Inside my `WordPressCustompagetype` template, non-relevant fields excluded:

```graphql
query ($id: ID!) {
  custom: WordPressCustompagetype(id: $id) {
    imageDownloaded {
      image
    }
    acf {
      bannerImage {
        sourceUrl
      }
    }
  }
}
```

I can output the field `$custom.acf.bannerImage.sourceUrl` and see the full URL of the image. It's held in an Advanced Custom Fields image field and I can return the image ID, an object, or a URL. 

When I inspect the imageDownloaded field in the __explore tab, I see:

```graphql
        imageDownloaded {
          image
        }
```

It returns a null value.

And if I use `$custom.imageDownloaded.image` in the template the page goes blank.

I've tried a number of permutations of the plugin options, even trying the dotted notation path in the sourceField, no luck.

Any thoughts?

**Comment by noxify** [comment]
Hey @Rocketpilot,

correct me if I'm wrong, but the Assets are stored in their own Graphql Type ( / Collection ) in gridsome.

Could you give it a try with the asset collection?

**Comment by noxify** [comment]
Something like this:

```
{
  use: '@noxify/gridsome-plugin-remote-image',
    options: {
      typeName: 'WordPressAttachment',
      sourceField: 'sourceUrl', // here you have to check if this is the correct field
      targetField: 'imageDownloaded',
      targetPath: './src/remoteImages',
    },
},
```

**Comment by Rocketpilot** [comment]
"Assets are stored in their own Graphql Type" - where is this discussed in the docs (edit: gridsome docs, that is)? I am not exactly a javascript guru (one reason Gridsome has been so appealing as it's very configuration-based) so I'm not sure what to do with this information.

I have been able to query in the explorer:

```graphql
  assets: allWordPressAttachment {
    edges {
      node {
        id
        altText
        imageDownloaded
      }
    }
  }
```

And it does return what I think you'd expect it to, but I don't really know how to operationalise this. How would I connect that so that the right attachment is connected to the post? Forgive me if that's outside the scope of the plugin but I'm basically stretching the limit of my understanding of Gridsome right now.

**Comment by noxify** [comment]
Hi @Rocketpilot ,

if I understood you correctly, the image download was successful.
This means:
1. In `WordpressAttachment` you can see the field `imageDownloaded`. This field has the type `Image` ( or `[Image]` in case the source field contains multiple urls )
2. You can see the downloaded image in the specified `targetPath` ( e.g. `./src/remoteImages` )


> but I don't really know how to operationalise this. How would I connect that so that the right attachment is connected to the post?

Since the plugin extends the existing schema, everything should work as before, you only have to update your post query to get the local image instead of the image url

```
query {
   allWordpressPost {
     edges {
       node {
          id
          preview_image {
            imageDownloaded
          }
       }
    }
  }
}
```

`preview_image` is just an example - it's the name of the field in the `WordpressPost` collection.

The wordpress source creates automatically the relation between the `WordpressPost` and `WordpressAttachment`.

Does this help?

**Comment by Rocketpilot** [comment]
I'll need to play around with this a bit more but -- yes it works! 

Incidentally, caching images locally from a remote source is the first use-case that came to mind when I discovered integrating headless CMSes with tools like Gridsome and it's almost never addressed in any user guides or official documentation, so thank you for taking the time to spell it out.

**Comment by noxify** [comment]
I will close this issue for now - If there is something else, feel free to create a new issue or reopen this one :)
