### ISSUE TITLE
 Cannot read property 'findNode' of undefined

### ISSUE THREAD

**Issue by yulafezmesi** [noxify/gridsome-plugin-remote-image#28]
When tried to implement Metadata type, I'm getting this error. Is there any way to implement core Metadata type without a collection?

 Cannot read property 'findNode' of undefined

```json
 {
      use: '@noxify/gridsome-plugin-remote-image',
      options: {
        typeName: 'Metadata',
        sourceField: 'image',
        targetField: 'imageDownloaded',
        targetPath: './src/assets/remoteImages',
      },
    },
```

**Comment by madex1** [comment]
i have the same problem
```
TypeError: Cannot read property 'findNode' of undefined
    at ImageDownloader.getFieldType ...
```
when i'm using **@noxify/gridsome-plugin-remote-image** with **@gridsome/source-graphql** source plugin.

nodeCollection is undefined here:
```
getFieldType(api, options) {
        
        const nodeCollection = api._app.store.getCollection(options.typeName);
```
when this function is called here:
```
api.createSchema(({ addSchemaTypes }) => {
            const fieldType = this.getFieldType(api, options);
            this.generateSchemaType(addSchemaTypes, fieldType);
        });
```
it seems like collections are not loaded when this code is running :(

i've got **typeName** value from localhost:8080/__explore, so it should work as i suggest :)

Can you help me?

**Comment by noxify** [comment]
Hi,

sorry for the delay.

Currently the plugin doesn't work with the graphql source.

The problem is, that the external graphql source isn't imported into the gridsome graphql.

Currently I have no glue how to solve it.

**Comment by madex1** [comment]
Ok, thanks.
Please add this information to docs

**Comment by noxify** [comment]
Docs updated :)

https://github.com/noxify/webstone.info/blob/master/content/documentation/gridsome-plugin-remote-image/index.md#graphql-data-source


Result: https://webstone.info/documentation/gridsome-plugin-remote-image/
