### ISSUE TITLE
Rename package to `gridsome-plugin-remote-images`

### ISSUE THREAD

**Issue by hacknug** [noxify/gridsome-plugin-remote-image#7]
I feel like using the plural form is the way to go here (`images` instead of `image`). Better to change it now (if you agree) before people start using it on their projects.

I will update the README later to use the npm package name now that's been published (even if it's not renamed) 👍

**Comment by noxify** [comment]
sure

**Comment by dsturm** [comment]
@hacknug, good catch 👍

**Comment by noxify** [comment]
We did it in the "new" repo: https://github.com/jammeryhq/gridsome-plugin-remote-images
