### ISSUE TITLE
Getting Error: Cannot find module '@noxify/gridsome-plugin-image-download'

### ISSUE THREAD

**Issue by gabriel4649** [noxify/gridsome-plugin-remote-image#9]
Hey!

Thanks for building this. 

I'm trying to get it to work but I can't get it to find the module. I'm getting `Error: Cannot find module '@noxify/gridsome-plugin-image-download'`

Gridsome config

```
// This is where project configuration and plugin options are located. 
// Learn more: https://gridsome.org/docs/config

// Changes here require a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`

module.exports = {
  siteName: 'Indie Hackers Puerto Rico',
  plugins: [
    {
      use: 'gridsome-source-google-sheets',
      options: {
        sheetId: process.env.GOOGLE_SHEET_ID,
        apiKey: process.env.GOOGLE_API_KEY,
        // type: 'TYPE_NAME', //Optional - default is googleSheet. Used for graphql queries.
      }
    },
    {
      use: '@noxify/gridsome-plugin-image-download',
      options: {
        'typeName' : 'GoogleSheet',
        'sourceField': 'image',
        'targetField': 'imageDownloaded',
        'targetPath': './src/assets/remoteImages'
      }
    }
  ]
}
```

I installed the module using `yarn add https://github.com/noxify/gridsome-plugin-remote-image.git` and verified that the code is actually there in `node_modules`

**Comment by noxify** [comment]
Hi @tatsuhirosatou,

thanks for the report. 

I have to check this ASAP but unfortunately you have to wait until tomorrow evening.

In the meantime, please use the github link to get the package. You can find the command (for yarn and npm) in the readme.

Thanks and have a nice weekend.

Regards,
Marcus

**Comment by gabriel4649** [comment]
Sure, take your time. 

Yeah, I use the command on the readme.

**Comment by gabriel4649** [comment]
I was able to make it work by setting `use: '~/node_modules/@noxify/gridsome-plugin-image-download/',`

That said it seems to not work with `gridsome-source-google-sheets`

Or maybe it is not running at all. I'm setting some `console.log` at the top of `constructor(api, options)` and they are not printing.

**Comment by dsturm** [comment]
Hey @tatsuhirosatou, can you please post your package.json - the mentioned module name (`@noxify/gridsome-plugin-image-download`) makes me curious, since it´s the old package name.

**Comment by noxify** [comment]
Hi,

i have checked the npm registry but can't found the mentioned name.

If I run this in the terminal, it works as expected.

```
npm i -s @noxify/gridsome-plugin-remote-image
+ @noxify/gridsome-plugin-remote-image@1.0.0
added 29 packages from 19 contributors and audited 34274 packages in 13.952s
```

As @dsturm already said, it seems you have used the old package name, which isn't working anymore.
( I had to rename the package, because `download` is a reserved word for `npm` )

I will close this issue for now - If there are any questions, feel free to reopen the issue.

Thanks & Regards,
Marcus

**Comment by gabriel4649** [comment]
Alright, I figured out the issue. 

The README needs an update ;)

It still references the old package name.

**Comment by dsturm** [comment]
Yep, thanks 🙄 I've updated the readme / example.
